### ISSUE TITLE
Console error (only sometimes)

### ISSUE THREAD

**Issue by Eldenroot** [martec/automention#16]
Sometimes I (and other users) get this error in console

![image](https://user-images.githubusercontent.com/778890/109050344-9386d500-76d9-11eb-8000-b308e1a27eaf.png)

Unfortunately quite tricky and difficult to reproduce (I do not how to reproduce). It happens every day. I use your latest version with tables, imgur upload and highlight modules.

The editor is not loaded when you get this error.

**Comment by martec** [comment]
Hi,

Sorry but this is probably not related to this plugin. For the error shown by you are not showing anything related to this plugin. 

The error message is saying that one of the files is loading after the other, which should be the other way around. 
That is, this most likely must be some plugin you are using that is changing the way pages are loaded. Page loader accelerator (asynchronous JavaScript loader) this includes rocket loader from cloudflare, ajax load pages like Endless or ThunderBoard of Shade etc.

**Comment by Eldenroot** [comment]
I dont use any of these:

`Page loader accelerator (asynchronous JavaScript loader) this includes rocket loader from cloudflare, ajax load pages like Endless or ThunderBoard of Shade etc.`

**Comment by martec** [comment]
Sorry, but I can’t do anything about it, because it’s not possible to reproduce. 

You can try to figure out how to reproduce this. 

One way to do this is to test with a clean install on localhost. 
And go testing one plugin per plugin until you find out which plugin could be causing this type of conflict.

Sorry, but I don't have time to do this for you. So, unfortunately, it won't do me any good to give me the list of plug-ins you use. Not to mention that the configuration of each plugin you use can also interfere.

For information only, XThreads usually creates conflicts with Rin Editor. Anyway, you will find out if you test with a clean install.
